# Config generated 2015-05-14 18:36:59

display:
  borderless-fullscreen: false
  resolution: [1080, 768]

game:
  humans:
    spawn-count: 5
    wandering:
      active: true
      move: true

  buildings:
    strobe-lights: true

debug:
    log-level: debug

